services:
  speedtest:
    build: .
    container_name: speedtest
    user: ${PUID}:${PGID}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    restart: no
    networks:
      - speedtest

networks:
  speedtest:
    name: speedtest
