[global]
    workgroup = WORKGROUP
    server string = Batlab
    server role = standalone server
    security = user
    map to guest = never
    restrict anonymous = 2

    interfaces = lo enp5s0
    bind interfaces only = yes
    smb ports = 445

    server min protocol = SMB3
    server max protocol = SMB3
    server smb encrypt = required

    hosts allow = 127.0.0.1 192.168.1.0/24
    hosts deny = 0.0.0.0/0

    load printers = no
    disable spoolss = yes
    usershare allow guests = no

[media]
    path = /mnt/storage/data/media

    vfs objects = catia fruit streams_xattr
    fruit:encoding = native
    fruit:resource = file
    fruit:metadata = netatalk
    fruit:locking = none
    fruit:time machine = no

    browseable = yes
    guest ok = no

    read only = yes
    valid users = potato @media-readers
    write list = potato

    force group = potato
    create mask = 0664
    directory mask = 0775

    follow symlinks = no
    wide links = no
